### ISSUE TITLE
sClass vs className

### ISSUE THREAD

**Issue by williamyiu** [NullRefExcep/yii2-datatables#50]
With your release of 1.1.0, I noticed that you are using sClass, however, the official datatable field is className which I have used in 1.0.4.

Here is a reference:
https://datatables.net/reference/option/columns.className

Please advise.

Thanks

**Comment by ZAYEC77** [comment]
I guess using `className` could make some confusion because we have `className` method at Yii2.
Filed `sClass` works with Datatables version 1.10.19.
While this property will be work, I guess it's better to use it.
If you have some problems with it, you could try to use version 1.0.4 if you don't have any issue with it.

In another case, we could discuss changing this property at next version.

**Comment by Radon8472** [comment]
@williamyiu Is the answer okay for you, or is there anything todo for this issue?

**Comment by williamyiu** [comment]
Yes, thank you
